package iota  //#=cats
package iotaz //#=scalaz
package internal

import cats.arrow.FunctionK         //#=cats
import scalaz.NaturalTransformation //#=scalaz

//#+cats
/** This exists soley as a marker for `FunctionK`s generated by iota
  * macros
  */
trait FastFunctionK[F[_], G[_]] extends FunctionK[F, G]
//#-cats

//#+scalaz
/** This exists soley as a marker for `NaturalTransformations`s generated by iota
  * macros
  */
trait FastNaturalTransformation[F[_], G[_]] extends NaturalTransformation[F, G]
//#-scalaz
