language: scala

jdk:
- oraclejdk8

scala:
- 2.11.12
- 2.12.4

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_3b783b5a7537_key -iv $encrypted_3b783b5a7537_iv -in secring.asc.enc -out secring.asc -d;
  fi

script:
- sbt ++$TRAVIS_SCALA_VERSION clean compile test

stages:
  - test
  - validate
  - deploy

jobs:
  include:
    - stage: validate
      script:
        - sbt ++$TRAVIS_SCALA_VERSION orgValidateFiles
        - sbt ++$TRAVIS_SCALA_VERSION tutReadme
      scala: 2.12.4
    - stage: deploy
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
            if grep -q "SNAPSHOT" version.sbt; then
              sbt ++$TRAVIS_SCALA_VERSION publish;
            else
              sbt orgUpdateDocFiles;
              git reset --hard HEAD;
              git clean -f;
              git checkout master;
              git pull origin master;
              sbt release;
              sbt depUpdateDependencyIssues;
            fi
          fi
      scala: 2.12.4

cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.coursier/cache -name "*.lock" -type f -delete
